### ISSUE TITLE
OutOfMemory error when handling big files

### ISSUE THREAD

**Issue by skonair** [SmartsquareGmbH/squit#17]
When we deal with big payloads (5-6MB in response files), we run into the following error at the end of the tests.

Problem in daemon expiration check
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.toArray(ArrayList.java:380)
        at java.util.ArrayList.<init>(ArrayList.java:178)
...
Expiring Daemon because JVM heap space is exhausted

**Comment by rubengees** [comment]
Memory usage has been improved in [6.0.3](https://github.com/SmartsquareGmbH/squit/releases/tag/6.0.3), so I'm closing for now.
